---
- name: Enable Rabbitmq Server Listener
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf

- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: Add user for queue to rabbitmq
  rabbitmq_user:
    user: usermq
    password: hruiW3mq
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: management
    state: present

- name: Apply settings
  service:
    name: rabbitmq-server
    state: restarted
    enabled: yes
  tags:
    - vagrant
