---
- name: Setup
  hosts: all
  remote_user: root
  become: yes
  vars:
    document_root: "{{ docroot | default ('/vagrant') }}"
    domain_name: "{{ simple_domain | default ('web.local') }}"
    php_version: "{{ php_default_version | default ('7.2') }}"
    mysql_version: "{{ mysql_default_version | default ('5.7') }}"
    mysql_root_pass: "{{ mysql_default_pass | default ('root') }}"
  become_method: sudo
  roles:
    - base
    - redis
    - nginx
    - php
    - mysql
    - mailcatcher
    - laravel
#    - rabbitmq
#    - supervisor
